mysite/mysite/apps/articles/urls.py
from django.urls import path


from . import views

app_name = 'articles'
urlpatterns = [
    path('', views.index, name = 'main'),
    path('<int:page>', views.index, name = 'main'),
    path('detail/<int:article_id>', views.detail, name = 'detail'),
]

mysite/mysite/apps/main/urls.py
from django.urls import path


from . import views

urlpatterns = [
    path('', views.main),
]

mysite/mysite/urls.py
from django.contrib import admin
from django.urls import path, include

from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('articles/', include('articles.urls')),
    path('', include('main.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

mysite/mysite/apps/articles/models.py
from django.db import models
from datetime import datetime, timedelta


class Article(models.Model):
    articl_title = models.CharField('Название статьи', max_length  = 200)
    articl_text = models.TextField('Текст статьи')
    articl_crucial = models.BooleanField('Ключевая', default = False)
    articl_actual = models.BooleanField('Список актуальных', default = False)
    articl_image = models.FileField('Фотография', blank=True, upload_to='images')
    date_modified = models.DateTimeField(auto_now=True)
    pub_date = models.DateTimeField('Дата публикации') 

    def was_changed_recently(self):
        if self.date_modified-self.pub_date >= timedelta(minutes=10):
            res = True
        else:
            res = False
        return res

    def __str__(self):
        return self.articl_title

    class Meta :
        verbose_name = 'Статья'
        verbose_name_plural = 'Статьи'

mysite/mysite/apps/gallery/models.py
from django.db import models

class Image(models.Model):
    title = models.CharField('Название', max_length  = 200)
    image = models.FileField(upload_to='images')
    

    def __str__(self):
        return self.title

    class Meta :
        verbose_name = 'Картинка'
        verbose_name_plural = 'Картинки'

mysite/mysite/apps/main/models.py
from django.db import models

# Create your models here.

mysite/mysite/apps/articles/views.py
from django.shortcuts import render
from django.http import Http404, HttpResponseRedirect
from django.core.paginator import Paginator

from .models import Article


def index(request, page = 1):
    articles_list = Article.objects.order_by('-pub_date')
    actual_articl = Article.objects.filter(articl_actual = True).order_by('-pub_date')[0]

    paginator = Paginator(articles_list, 10)
    page_obj = paginator.get_page(page)
    page_list = []
    date_title = 0
    for item in page_obj:
        if date_title != item.pub_date.strftime("%d %m %y"):
            date_title = item.pub_date.strftime("%d %m %y")
            page_list.append(date_title)
        page_list.append(item)
        

    context = {'articles_list':page_obj , 'actual_articl':actual_articl, 'page_list':page_list}
    return render(request, 'articles/list.html', context)

def detail(request, article_id):
    try:
        a = Article.objects.get( id = article_id)
    except:
        raise Http404('Статья не найдена!')
    
    context = {'article': a}
    return render(request, 'articles/detail.html', context)

mysite/mysite/apps/gallery/views.py
from django.shortcuts import render

# Create your views here.

mysite/mysite/apps/main/views.py
from django.shortcuts import render

from articles.models import Article
from django.http import HttpResponse
import datetime


# Create your views here.
def main(request):
    latest_articles_list = Article.objects.order_by('-pub_date')
    context = {'latest_articles_list':latest_articles_list}
    return render(request, 'main/main.html', context)

mysite/mysite/templates/articles/detail.html
{% extends 'base.html' %}

{% block title %}{{article.articl_title}}{% endblock %}

{% block content %}
    <h1>{{article.articl_title}}</h1>
    
    <img style="width: 512px;" src="/{{ article.articl_image }}" alt="img">
    <p>{{article.articl_text}}</p>
    <em>{{article.pub_date}}</em>
    <hr>
    
{% endblock %}

mysite/mysite/templates/articles/list.html
{% extends 'base.html' %}

{% block title %}Последние стати{% endblock %}

{% block content %}
<div class="row">
    <div class="col s8">
        {% if articles_list %}
            <div class="row">
                <div class="s12 m7">
                <div class="card">
                    <div class="card-image">
                    <img style="width: 100%; height: auto;" src="/{{ actual_articl.articl_image }}" alt="img">
                    </div>
                    <div class="card-action">
                        <a href="{% url 'articles:detail' actual_articl.id %}">{{actual_articl.articl_title}}</a>
                    </div>
                    <div class="card-content">
                    <p>{{actual_articl.pub_date}}</p>
                    </div>
                </div>
                </div>
            </div>



            <div class="row">
                <h1 class="widget-heading">Лента новостей</h1>
            </div>


            <div class="row">
                <ul class="collection">
                {% for a in page_list %}
                    {% if not a.pub_date %}
                        <li class="collection-item-news-feed-divider">
                            <div class="news-feed-divider">
                                {{a}}
                            </div>
                        </li>
                    {% elif a.articl_crucial %}
                        <li class="collection-item">
                            <span class="time">{{a.pub_date|time:"H:i"}}</span>
                            <a style="font-weight: 900;"  href="#">{{a.articl_title}}!</a>
                            {% if a.was_changed_recently %}
                                <span style="color: white;padding: 2px;border-radius: 10%;font-size: 10px;background-color: blue;">Обновлено</span>
                            {% endif %}
                            {% if a.articl_image %}
                                <span>
                                    <i style="position: absolute;" class="material-icons">camera_alt</i>
                                </span>
                            {% endif %}
                        </li>                    
                    {% else %}
                        <li class="collection-item 11" >
                            <span class="time">{{a.pub_date|time:"H:i"}}</span>
                            <a href="#">{{a.articl_title}}</a>
                            {% if a.was_changed_recently %}
                                <span style="color: white;padding: 2px;border-radius: 10%;font-size: 10px;background-color: blue;">Обновлено</span>
                            {% endif %}
                        </li>
                    {% endif %}
                    
                {% endfor %}
                </ul>  
            


                <ul class="pagination">
                    {% if articles_list.has_previous %}
                    <li class="waves-effect"><a href="{{ articles_list.previous_page_number }}"><i class="material-icons">chevron_left</i></a></li>
                    <li class="waves-effect"><a href="1">1</a></li>
                    {% else %}
                    <li class="disabled"><a href="#!"><i class="material-icons">chevron_left</i></a></li>
                    {% endif %}
                    {% if articles_list.number >= 3 %}
                        <li class="disabled"><a href="#!">...</a></li>
                        <li class="waves-effect"><a href="{{ articles_list.previous_page_number }}">{{ articles_list.previous_page_number }}</a></li>
                    {% endif %}
                    <li class="active"><a href="#!">{{ articles_list.number }}</a></li>
                    {% if articles_list.next_page_number < articles_list.paginator.num_pages %}
                        <li class="waves-effect"><a href="{{ articles_list.next_page_number }}">{{ articles_list.next_page_number }}</a></li>
                        <li class="disabled"><a href="#!">...</a></li>
                    {% endif %}
                    {% if articles_list.has_next %}
                    <li class="waves-effect"><a href="{{ articles_list.paginator.num_pages }}">{{ articles_list.paginator.num_pages }}</a></li>
                    <li class="waves-effect"><a href="{{ articles_list.next_page_number }}"><i class="material-icons">chevron_right</i></a></li>
                    {% else %}
                    <li class="disabled"><a href="#!"><i class="material-icons">chevron_right</i></a></li>
                    {% endif %}
                  </ul>
                            
            </div>  
        {% else %}
            Статьи не найдены!
        {% endif %}
    </div>
    <div class="col s4">6-columns (one-half)</div>
</div>
{% endblock %}

mysite/mysite/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %}Новостной Сайт{% endblock%}</title>


    <!--Import Google Icon Font-->
    <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
    <!-- Compiled and minified CSS -->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/css/materialize.min.css">
    <!--Let browser know website is optimized for mobile-->
    <meta name="viewport" content="width=device-width, initial-scale=1.0"/>

    <style type="text/css">

.collection-item-news-feed-divider {
  font-weight: 500;
  font-size: 18px;
  color: #6d6d6d;
  padding: 10px 0;
  position: relative;
}

.collection-item-news-feed-divider div{

    background: #fff;
    padding: 0 10px 0 0 !important;
    position: relative;
    z-index: 2;
    display: inline-block;
}
.collection-item-news-feed-divider::before {
  content: '';
  border-top: 1px solid #c7cccf;
  left: 0;
  right: 10px;
  position: absolute;
  top: 50%;
  z-index: 1;
}

a {
  text-decoration: none;
  color: #222629;
}
    
.collection {
  border: none;
}
     
.collection .collection-item {
line-height: 1.3;
display: block;
font-size: 18px;
letter-spacing: .0015em;
position: relative;
padding: 7px 0 10px 50px;
border-bottom: none;
}

.collection .collection-item .time {
  position: absolute;
  margin-bottom: 8px;
  line-height: 1.2;
  display: block;
  left: 0;
  top: 11px;
  font-size: 14px;
  font-weight: 500;
}
    </style>

</head>
<body>
    <!-- blue-grey lighten-1  -->
    <header>
        <nav class="transparent">
            <div class="nav-wrapper container">
                <a href="#!" class=" brand-logo center"><span class="blue-text">U</span><span class="yellow-text">k</span></a>
                <ul class="left hide-on-med-and-down">
                    <li>
                        <div class="switch">
                            <label>
                            UA
                            <input type="checkbox">
                            <span class="lever"></span>
                            EN
                            </label>
                    </div>
                    </li>
                </ul>
                <ul class="right hide-on-med-and-down">
                    <li><a href="sass.html"><i class="grey-text material-icons">search</i></a></li>
                </ul>
            </div>
        </nav>
        <nav class="blue darken-3">
            <div class=" container">
                <ul style="height: auto; display: flex; justify-content: center; width: 100%;">
                    <li><a href="{% url 'articles:main' %}">NEWS</a></li>
                    <li><a href="collapsible.html">DAILY</a></li>
                    <li><a href="collapsible.html">STYLER</a></li>
                    <li><a href="collapsible.html">TRAVEL</a></li>
                </ul>
            </div>
        </nav>
                
    
    </header>


    <div class="container">
        {% block content %}{% endblock %}
    </div>

     <!-- Compiled and minified JavaScript -->
     <script src="     https://cdnjs.cloudflare.com/ajax/libs/jquery/3.7.0/jquery.min.js"></script>
     <script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/js/materialize.min.js"></script>
</body>
</html>

mysite/mysite/templates/main/main.html
{% extends 'base.html' %}

{% block title %}Главная страница{% endblock %}

{% block content %}
 
    {% if latest_articles_list %}
        
        {% for a in latest_articles_list %}
            <a href="{% url 'articles:detail' a.id %}">{{a.articl_title}}</a>
        {% endfor %}

    {% else %}
        Статьи не найдены!
    {% endif %}

{% endblock %}